name: Deploy to Server at Home
on:
  push:
    branches: [ "release" ]

jobs:
  deploy:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install; pnpm run build; cp -r dist/* /var/www/html
